name: Continuous Integration
on:
    push:
        branches: [main]

jobs:
    CI:
        name: Continuous Integration
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

    